### ISSUE TITLE
Please extend this plugin to support IOS 

### ISSUE THREAD

**Issue by aravind816** [shinewanna/BackgroundSmsPlugin#5]
Dear developer,
  I am very impressed with this package. Only drawback is I could not use it for IOS app development. I have a requirement to send messages in background without opening the messaging app.
  Your plugin helped to achieve the feature in android app. 
  Would be great if you could extend this plugin to support IOS as well.

**Comment by shinewanna** [comment]
iOS is not allow like Android, u can't send directly in iOS.
